server:
  port: 8080
  servlet:
#    context-path: /api
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

spring:
  application:
    name: wardrobe-api
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.76.206.153:3306/wardrobe?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: admin
    password: ymumwKotcoq(
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

# 静态资源访问配置
  web:
    resources:
      static-locations: classpath:/static/

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wardrobe.model.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# JWT配置
jwt:
  secret: luke
  expiration: 604800 # Token有效期7天

# 微信小程序配置
wx:
  miniapp:
    appid: wx5c20fcf5ac7910e6
    secret: 45c8a30261a89215a4b4d52fae276f5f

# 文件上传配置
file:
  upload-path: //Users/youniverse/Wardrobe-API/Wardrobe-API/src/main/resources/static/upload/